# docker-compose.yml
version: '3.9'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: pnpm run start

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authmv
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
